version: "3.7"

services:
  jwilder-proxy:
    image: jwilder/nginx-proxy
    ports:
      - '80:80'
    environment:
      DEFAULT_HOST: pihole.glados.lan
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Denver'
      WEBPASSWORD: 'rawboned sleek divorcee meteoric oldster wadding'
      ServerIP: 192.168.0.11
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: pihole.glados.lan
      VIRTUAL_PORT: 80
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  parking:
    image: tylerdoll/better_parking_permits
    volumes:
      - ./better-parking-permits/src:/app
    environment:
      VIRTUAL_HOST: parking.glados.lan
      VIRTUAL_PORT: 80
    restart: unless-stopped
