version: "3.7"
services:
    nginx:
        image: nginx
        restart: always
        volumes:
            - ./nginx/nginx.conf:/etc/nginx

    parking:
        image: tylerdoll/better_parking_permits
        restart: always
